
all:
	make calculate
	make assignment3

calculate:
	gcc -Wall calculate.c -o calculate

assignment3:
	gcc -Wall assignment3.c -o assignment3.exe

clean:
	rm -f assignment3PIPE
	rm -f calculate
	rm -f assignment3.exe